### PR TITLE
fix(loadLibrary): prefix all module paths with `file:///` before dynamically importing them

### LINKED ISSUE #744: Can't get it to work with the built-in SCM input
List of things I have done:
- installed commitlint;
- added a commitlint.config.js file;
- validated with commitlint --from=HEAD~1
- downloaded the extension;
- tried to commit an invalid message via built-in SCM input.

on the last step nothing happened and the invalid message was commited with no warnings.

Is there something I'm missing?

### PR DESCRIPTION
**Pull request by BinToss**
Fixes #744, but opens the path to previously inaccessible bugs e.g.
RangeError: Found rules without implementation: extends.
I'll address that with a second PR.

The cause of ERR_UNSUPPORTED_ESM_URL_SCHEME errors is typically Node.js's Require/Import functions lacking special behavior for Windows file paths i.e. any path beginning with a drive letter followed by a colon (e.g. `C:\`).

The fix: pathToFileURL(path).href

### CODE REVIEW

File: src/worker/loadLibrary.ts [hunk 1]
```diff
@@ -35,7 +36,7 @@ const unwrapDefaultExport = <T>(module: T): UnwrapDefault<T> => {
 };
 
 const importDefaultExport = async <T>(path: string) => {
-  const result = (await import(path)) as T;
+  const result = (await import(pathToFileURL(path).href)) as T;
```
Comment (joshbolduc) [inline src/worker/loadLibrary.ts]: This codepath runs for all imports, including when we're importing copies of commitlint bundled with the extension itself. In that case, `path` is really a package name, so we don't want to treat it as a URL.

**Review by joshbolduc — COMMENTED** [review]
Thanks for digging into this! I noticed a regression when using bundled commitlint but it's a simple fix so I pushed it up.

File: src/worker/loadLibrary.ts (hunk 1 above)
Comment (BinToss) [reply src/worker/loadLibrary.ts]: Ooooh, right! My breakpoints were only in the codepaths where the modules' absolute paths were passed in, so I hadn't considered that.

**Comment by BinToss** [comment]
Darn. I just noticed an issue when running the test suite. I'm too accustomed to tests being in a tests sub-directory, so I missed that there were tests in src...shame on me.



I've traced it to a `path:resolve` call () returning a different path than expected:
https://github.com/joshbolduc/vscode-commitlint/blob/48cb7e14a7cc71837af8191823a826ce41f20a4a/src/worker/loadLibrary.ts#L50-L56

```ts
      // 'C:\\Repos\\BinToss\\joshbulduc.vscode-commitlint\\test\\commitlint\\v11\\@commitlint\\cli'
      const relativeCommitlintCli = resolve(path, '@commitlint', 'cli')
      // "C:\\Repos\\BinToss\\joshbulduc.vscode-commitlint\\test\\commitlint\\v11\\commitlint"
      const relativeCommitlint = resolve(path, 'commitlint');
      // 'C:\\Repos\\BinToss\\joshbulduc.vscode-commitlint\\node_modules\\@commitlint\\load\\lib\\load.js'
      const resolvePath = require.resolve(name, {
        paths: [
          path,
          relativeCommitlintCli,
          relativeCommitlint,
        ],
      });
```

<details><summary>I wondered if it was an OS/platform problem, so I wrapped the path in pathToFileURL(...).href. This did not affect the end result.</summary>

```ts
      // 'file:///C:/Repos/BinToss/joshbulduc.vscode-commitlint/test/commitlint/v11/@commitlint/cli'
      const relativeCommitlintCli = pathToFileURL(resolve(path, '@commitlint', 'cli')).href;
      // 'file:///C:/Repos/BinToss/joshbulduc.vscode-commitlint/test/commitlint/v11/commitlint'
      const relativeCommitlint = pathToFileURL(resolve(path, 'commitlint')).href;
      // 'C:\\Repos\\BinToss\\joshbulduc.vscode-commitlint\\node_modules\\@commitlint\\load\\lib\\load.js'
      const resolvePath = require.resolve(name, {
        paths: [
          path,
          relativeCommitlintCli,
          relativeCommitlint,
        ],
      });
```
<details>

What the heck is going on?
`require.cache` doesn't have any cached imports for commitlint's load.js.

Although the test fails, the extension works as intended. At runtime and while debugging, the local/global, dynamic imports are resolved to their respective `node_modules` paths.

**Comment by joshbolduc** [comment]
You probably need to run `npm run test:prep` to set up all the test projects--or at least run `npm ci` within `test/commitlint/v11`. If the test project dependencies aren't there, it will resolve to the wrong path like you are seeing.

**Comment by BinToss** [comment]
Ooooohhhh....Not running test:prep would definitely lead to incorrect results...My bad.

I'll have to modify the script to utilize cross-env to make the script work on Windows.

> 'TS\_NODE\_PROJECT' is not recognized as an internal or external command,  
> operable program or batch file.

---

after `npm i -D cross-env` and prepending `test:prep` with `cross-env` , , I'm still seeing the same, incorrect import paths...

It turns out that the spawnSync call in testPrep.ts wasn't set up for cross-platform execution. It would silently fail (NOENT). So, I copied `process.platform === 'win32' ? 'npm.cmd' : 'npm'` from `getSystemGlobalLibraryPath.ts` to get it working.

That still didn't get it working. It instead returned `EINVAL` errors. This is due to a [Node.js security update from 2024](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high). Luckily, that blog post provides a solution. 

---
